version: '3.8'

services:
  frontend:
    container_name: market-frontend
    build:
      context: src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    container_name: market-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - my-network

  postgresql:
    image: postgres
    container_name: market-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stockMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - my-network

networks:
  my-network:
    driver: bridge